[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"

[project]
name = "mlflow_launch"
version = "1.1.2"
description = "A simple module to launch the MLflow server from Python."
requires-python = ">=3.6"
readme = "README.md"
dependencies = []
[[project.authors]]
name = "Jason Conner"
email = "jason.conner@noaa.gov"

[project.scripts]
mlflow-launcher = "mlflow_launch.__main__:main"

[tool.bumpversion]
current_version = "1.1.2"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "mlflow_launch/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[tool.bumpversion.parts.prerelease]
values = ["dev", "rc"]